version: '3'

services:

  nginx:
    container_name: "nginx"
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app

  php:
    container_name: "php"
    build: ./
    environment:
      PHP_IDE_CONFIG: "serverName=messenger"
    volumes:
      - ./:/app

  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin:latest
    restart: on-failure
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  mysql:
    container_name: "mysql"
    image: mysql:8.0
    ports:
      - '5506:3306'
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messenger

    volumes:
      - 'db-data:/usr/local/mysql/data'

  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  db-data: ~